TARGET: exec

exec:
	gcc -g code1_int.c -o code1_int.exe
	gcc -g code2_raise.c -o code1_raise.exe
	gcc -g code3_kill_sender.c -o code3_kill_sender.exe
	gcc -g code3_kill_rx.c -o code3_kill_rx.exe

clean:
	rm *.o *.exe
